### ISSUE TITLE
[BUG] Thread icon not aligned

### ISSUE THREAD

**Issue by Minibus93** [schnensch0/zelk#14] opened 2021-07-29 08:29 UTC
**Describe the bug**
The thread icon is not aligned to the other icons in the row

**To Reproduce**
1. Update discord to Stable 91552 (or whichever version of the branch you use that added threads)
2. Look at top right

**Screenshots**
![Immagine](https://user-images.githubusercontent.com/73554423/127458753-2fbbabf2-2b3d-49d0-af73-12ee342b1596.png)

**Setup**
 - OS: w10 
 - Client Mod: GooseMod
 - Release Channel: Stable
 - Enabled Themes: Zelk 1.2
 - Enabled Plugins: Fucklytics, Silent typing

**Comment by schnensch0** [comment] 2021-07-29 11:52
Can't reproduce. Are you on the latest version? Try uninstalling and reinstalling Zelk. Do you have any Custom CSS snippets?

**Comment by Minibus93** [comment] 2021-07-29 12:14
No Custom CSS snippets.


These are the info that GM gives me:

- Stable 91552 (7f06584) 
- Host 1.0.9002 
- Windows 10 64-Bit (10.0.19042)
- GooseMod 10.1 (77765b3)
- GooseMod Ext 1.2.0
- GM Storage Extension


Things I've tried: 
- Uninstalling and re-installing Zelk (no success)
- Deleting GooseMod cache (no success)
- Re-installing GooseMod (no success)
- Uninstalling & Re-installing Discord and GooseMod (no success)

I don't know if it's relevant, but now that I have reinstalled GooseMod I have 3 total enabled plugin:
- Fucklytics
- Silent Typing
- Custom CSS (never used though)

**Comment by schnensch0** [comment] 2021-07-29 12:37
that's really weird. I replicated this exact setup (except my windows build being 10.0.19043, which shouldn't make a difference) with no issue. could you open the inspector (ctrl+shift+i), select the threads icon and see if this is in the styles:
![grafik](https://user-images.githubusercontent.com/58988092/127492826-559e05df-6d7d-4eb8-9d29-254a27034d18.png)

**Comment by Minibus93** [comment] 2021-07-29 13:36
Here is what the inspector shows to me, it's a bit different:

![Senza titolo-1](https://user-images.githubusercontent.com/73554423/127501646-4e96ecf7-7c40-43c8-bae1-5486f7fe22f5.png)

**Comment by schnensch0** [comment] 2021-07-29 14:05
fixed in https://github.com/schnensch0/zelk/commit/192bba6f07ab7c34c563942c7c127cbba5fa860e

**Closed by schnensch0** 2021-07-29 14:05 UTC
Labels: bug

**Comment by n0tsteve** [comment] 2021-09-16 13:49
This issue is persistent again.
Stable 97507 (370981f)
BetterDiscord 1.2.1
Host 0.0.15
Linux 64-Bit (5.14.2-Zen1-2-Zen)
Zelk 1.2
![20210916_15h47m47s_grim](https://user-images.githubusercontent.com/63497413/133623992-098b4b9e-76e3-465e-98a2-0619756192de.png)

**Comment by schnensch0** [comment] 2021-09-18 06:04
discord language?

**Comment by n0tsteve** [comment] 2021-09-18 06:12
Hungarian

**Comment by n0tsteve** [comment] 2021-09-18 06:13
I only modified the colors and nothing else

**Comment by schnensch0** [comment] 2021-09-18 06:41
It's dependent on the language, I'll fix it for Hungarian

**Comment by schnensch0** [comment] 2021-10-30 10:14
fixed in https://github.com/schnensch0/zelk/commit/d94a0b11e1b0c809472216f8d59eba0168ca9d54
